#!/bin/bash

CURL_OPTION="-v"

set -e

cd "${1}"

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
#set -x

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > "${payload}" <&0

disable="$(jq -r '.source.disable // "false"' < "${payload}")"
if [[ "$disable" == "true" ]]
then
  echo "Notifications disabled"
  exit
fi

debug="$(jq -r '.params.debug // "false"' < "${payload}")"
color="$(jq -r '.params.color // "00EA43"' < "${payload}")"

tailLines="$(jq -r '.params.tailLines // ""' < "${payload}")"
[[ -z "${tailLines}" ]] && tailLines=10

textFile="$(jq -r '.params.textFile // ""' < "${payload}")"
export TEXT_FILE_CONTENT=""
[[ -n "${textFile}" && -f "${textFile}" ]] && TEXT_FILE_CONTENT="$(tail -n $tailLines "${textFile}")"

actionName="$(jq -r '.params.actionName // "Open Concourse"' < "${payload}")"
actionTarget="$(jq -r '.params.actionTarget // "https://concourse.ci"' < "${payload}")"
title="$(jq -r '.params.title // "Concourse CI"' < "${payload}")"
activitySubtitle="$(jq -r '.params.activitySubtitle // ""' < "${payload}")"
text="$(jq -r '.params.text // "NO MSG"' < "${payload}")"

text=$(echo -n "$text" | envsubst)
actionName=$(echo -n "$actionName" | envsubst)
actionTarget=$(echo -n "$actionTarget" | envsubst)
title=$(echo -n "$title" | envsubst)
activitySubtitle=$(echo -n "$activitySubtitle" | envsubst)

#echo "$text"

body="$(cat <<EOF
{
  "@type": "MessageCard", 
  "@context": "http://schema.org/extensions", 
  "summary": "summary", 
  "title": "${title}", 
  "themeColor": "${color}", 
  "sections": [
    {"text": "${text}"},
    {"activitySubtitle": "${activitySubtitle}"}
  ],
  "potentialAction": [
    {
      "@context": "https://schema.org", 
      "@type": "ViewAction", 
      "name": "${actionName}", 
      "target": ["${actionTarget}"]
    }
  ]
}
EOF
)"

if [[ "$debug" == "true" ]]
then
  echo "$body"
  exit
fi

webhook_url="$(jq -r '.source.url' < "${payload}")"
redacted_webhook_url=$(echo "${webhook_url}" | sed -e 's#/\([^/\.]\{2\}\)[^/.]\{5,\}\([^/.]\{2\}\)#/\1…\2#g' | jq -R .)

url_path="$(echo ${webhook_url} | sed -e "s/https\{0,1\}:\/\/[^\/]*\(\/[^?&#]*\).*/\1/")"
curl ${CURL_OPTION} -d "${body}" "${webhook_url}" 2>&1 | sed -e "s#${url_path}#***WEBHOOK URL REDACTED***#g"

timestamp=$(date +%s)
metadata="$(cat <<EOF
{
  "version": {"timestamp": "${timestamp}"},
  "metadata": [
    {"name": "url", "value": ${redacted_webhook_url}},
    {"name": "actionName", "value": "${actionName}"},
    {"name": "actionTarget", "value": "${actionTarget}"},
    {"name": "BUILD_PIPELINE_NAME", "value": "${BUILD_PIPELINE_NAME}"}
  ]
}
EOF
)"

echo "$metadata"  >&3

